### PR TITLE
scale canvas for higher resolutions

### PR DESCRIPTION
**Pull request by Alphazork**
Added a new prop called 'scale'. This can be used to scale the canvas for sharper drawing.
Example: Set the canvas size to width:1000px and height:500px, scale it down with css to 500x250px. Set scale to 2.
Image will be a lot sharper

### CODE REVIEW

**Review by razztyfication — CHANGES_REQUESTED** [review]
Hello, thank you for contributing.

I'll leave some note for you to fix before I merge it.

1. Please add your changes on file [src/VueDrawingCanvas.ts](https://github.com/razztyfication/vue-drawing-canvas/blob/master/src/VueDrawingCanvas.ts) instead. I'll remove dist folder on the next release.
2. Make sure your changes have no error with typescript strict type declaration "**_noImplicitAny_**"

**Comment by Alphazork** [comment]
I have added the features to typescript. Please check

**Comment by razztyfication** [comment]
Can you provide more information on what is this props will do on [README](https://github.com/razztyfication/vue-drawing-canvas/blob/master/README.md) file? Much better if you can provide any example.

**Comment by razztyfication** [comment]
Do you mind to check this [sandbox](https://codesandbox.io/s/vue-drawing-canvas-1010-rc1-d5y472)?

Look like I did some mistake to get it to work, it 's move a bit from cursor and the output seems not resizing

**Comment by Alphazork** [comment]
It was my mistake. Settings that work:
<vue-drawing-canvas
...
:width="1200"
:height="800"
:scale="2"
style="width=600px"
>

No parent element needed!

**Comment by razztyfication** [comment]
All right I'll keep it for later. Anyway thanks for your contribution.

**Pull request merged**
