### PR TITLE
added the ability to line brake by spliting text '\n'

### PR DESCRIPTION
**Pull request by mishahobanov**
hi, i am made little improvement on function 'wrapText'. I need to draw text from new line that is why i split the text into lines, and draw each separately.

### CODE REVIEW

**Comment by mishahobanov** [comment]
Hi, i want to achieved to display text from new line many times.
Under pic with sample 

image

Please review my new changes as soon as possible, thanks!)

**Comment by razztyfication** [comment]
Hello @mishahobanov 

i just got your point.
try this [sandbox](https://codesandbox.io/s/vue-drawing-canvas-1-0-4-beta-1-evuol) and tell me is this what you want to achieve?

**Comment by mishahobanov** [comment]
Yes bro

**Comment by razztyfication** [comment]
Updated version 1.0.4 with [example](https://github.com/razztyfication/vue-drawing-canvas/blob/v1.0.4/CHANGELOG.md)

i am closing this now. thanks

**Pull request closed without merging**
